name: taxlogic
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Stephen <email@example.com>

environment:
  sdk:

dependencies:

dev_dependencies:
  test:
